GET_FILENAME_COMPONENT(module_file_path ${CMAKE_CURRENT_LIST_FILE} PATH )

# Look for the header file
FIND_PATH( FMOD_INCLUDE NAMES fmod.h
           PATHS "${FMOD_INCLUDE_DIR}"
           DOC "Path in which the file fmod.h is located" )

FIND_LIBRARY( FMOD_LIBRARY NAMES fmod64_vc.lib
	PATHS "${FMOD_LIBRARY_DIR}"
	DOC "Path to where FMOD library is located" )

IF (FMOD_LIBRARY)
	SET (FMOD_FOUND 1)
ELSE()
	SET (FMOD_FOUND 0)
ENDIF (FMOD_LIBRARY)

IF(NOT FMOD_FOUND)
  SET(FMOD_MESSAGE
    "FMOD was not found. Make sure FMOD_LIBRARY_DIR and FMOD_INCLUDE_DIR are set")
  IF(FMOD_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "${FMOD_MESSAGE}")
  ELSEIF(NOT FBX_FIND_QUIETLY)
    MESSAGE(STATUS "${FMOD_MESSAGE}")
  ENDIF(FMOD_FIND_REQUIRED)
ENDIF(NOT FMOD_FOUND)