GET_FILENAME_COMPONENT(module_file_path ${CMAKE_CURRENT_LIST_FILE} PATH )

# Look for the header file
FIND_PATH( FREETYPE_INCLUDE NAMES freetype.h
           PATHS "${FREETYPE_INCLUDE_DIR}"
           DOC "Path in which the file freetype.h is located" )

FIND_LIBRARY( FREETYPE_LIB_DEBUG NAMES freetype.lib
	PATHS "${FREETYPE_LIBRARY_DIR}/Debug"
	DOC "Path to where the FreeType debug library is located" )
	
FIND_LIBRARY( FREETYPE_LIB NAMES freetype.lib
	PATHS "${FREETYPE_LIBRARY_DIR}/Release"
	DOC "Path to where the FreeType library is located" )
	
SET (FREETYPE_LIBRARY
	debug ${FREETYPE_LIB_DEBUG}
	optimized ${FREETYPE_LIB}
)

IF (FREETYPE_LIB AND FREETYPE_LIB_DEBUG)
	SET (FREETYPE_FOUND 1)
ELSE()
	SET (FREETYPE_FOUND 0)
ENDIF (FREETYPE_LIB AND FREETYPE_LIB_DEBUG)

IF(NOT FREETYPE_FOUND)
  SET(FREETYPE_MESSAGE
    "FreeType was not found. Make sure FREETYPE_LIBRARY_DIR and FREETYPE_INCLUDE_DIR are set")
  IF(FREETYPE_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "${FREETYPE_MESSAGE}")
  ELSEIF(NOT FREETYPE_FIND_QUIETLY)
    MESSAGE(STATUS "${FREETYPE_MESSAGE}")
  ENDIF(FREETYPE_FIND_REQUIRED)
ENDIF(NOT FREETYPE_FOUND)